# config/s3.yml
production:
  access_key_id: AKIAJLAPF2TQDXY7EZGA
  secret_access_key: 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
  bucket: freelaphotos
development:
  access_key_id: AKIAJLAPF2TQDXY7EZGA
  secret_access_key: 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
  bucket: freelaphotos