# config/s3.yml
production:
  access_key_id: AKIAJ4RJENH4ZVBB2K3Q
  secret_access_key: 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
  bucket: freelaphotos
development:
  access_key_id: AKIAJ4RJENH4ZVBB2K3Q
  secret_access_key: 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
  bucket: freelaphotos