# config/s3.yml
production:
  access_key_id: AKIAJJJ7GHPHIULSHH5A
  secret_access_key: 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
  bucket: freelaphotos
development:
  access_key_id: AKIAJJJ7GHPHIULSHH5A
  secret_access_key: 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
  bucket: freelaphotos