# config/s3.yml
production:
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
  bucket: freelaphotos
development:
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
  bucket: freelaphotos